name: Just run
on: workflow_dispatch
jobs:
  run-it:
    runs-on: ubuntu-latest
    env:
      TXT: "Hello, hello"
    steps:
    - uses: actions/checkout@v4
    - name: Run script
      run: python3 script.py
